### ISSUE TITLE
Conversion Help

### ISSUE THREAD

**Issue by micbrenn** [jsfenfen/texas_rrc#1]
Have you successfully converted these files to ASCII? I am trying to learn how to do this on my own, and am not sure where exactly to start. Could you get me started on the right track?

**Comment by jsfenfen** [comment]
No, that's not part of this repo. You can google ebcdic to ascii, though I believe it is the COMP or COMP-3 fields that require special attention. A bit more here: http://stackoverflow.com/questions/29232656/decoding-comp-3-packed-fields-in-an-ascii-file-in-python
